packages:
  - packages/*
  - packages/common/*
  - docs
  - playground
  - internal/*

catalog:
  unbuild: ^3.5.0
  reka-ui: ^2.1.1
  vue: ^3.5.13
  turbo: ^2.4.4
  vite: ^6.2.1
  tailwindcss: ^3.4.3
  tailwindcss-animate: ^1.0.7
  autoprefixer: ^10.4.20
  clsx: ^2.1.1
  tailwind-merge: ^3.0.2
  cssnano: ^7.0.6
  postcss: ^8.5.3
  postcss-import: ^16.1.0
  postcss-preset-env: ^10.1.5
  vee-validate: ^4.15.0
  lucide-vue-next: ^0.484.0
  class-variance-authority: ^0.7.1
  zod: ^3.24.2
  embla-carousel-vue: ^8.5.2
  vaul-vue: ^0.4.1
  vue-sonner: ^1.3.0
  lodash.get: ^4.4.2
  postcss-antd-fixes: ^0.2.0
  '@iconify/vue': ^4.3.0
  '@types/lodash.get': ^4.4.9
  '@types/postcss-import': ^14.0.3
  '@iconify/json': ^2.2.314
  '@iconify/tailwind': ^1.2.0
  '@manypkg/get-packages': ^2.2.2
  '@tailwindcss/nesting': 0.0.0-insiders.565cd3e
  '@tailwindcss/typography': ^0.5.16
  '@types/node': ^22.13.10
  '@vueuse/core': ^13.0.0
  '@unovis/ts': ^1.5.1
  '@unovis/vue': ^1.5.1
  '@vee-validate/zod': ^4.15.0